server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/temx
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  profiles:
    active: dev

jwt:
  auth:
    converter:
      resource-id: ${RESOURCE_ID}
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

